# constants.py

SCREEN_WIDTH, SCREEN_HEIGHT = 1280, 720
SCREEN_CENTER_X, SCREEN_CENTER_Y = SCREEN_WIDTH // 2, SCREEN_HEIGHT // 2
FPS = 60
HEIGHT_TO_REMOVE_OBJECT = 50 # pixels

GROUND_Y = 600
MAX_PLANT_Y = 100

MAX_SEGS_TO_HAVE = 500
INITIAL_SEGMENTS = 5
CONSOLIDATION_SEGMENTS = 3
BUFFER_SEGMENTS = 2
PLANT_SEGMENT_HEIGHT = 0.05 # meters
# calculate current height by the length of plant neck
STARTING_HEIGHT = (INITIAL_SEGMENTS) * PLANT_SEGMENT_HEIGHT  # 0.25 meters: size of rat
INITIAL_PIXELS_PER_METER = (GROUND_Y - MAX_PLANT_Y) / STARTING_HEIGHT

print(INITIAL_PIXELS_PER_METER*PLANT_SEGMENT_HEIGHT)
PLANT_BASE_SIZE = 0.1 # meters
PLANT_HEAD_H = 0.03694 # meters
PLANT_HEAD_W = 0.1 # meters
# PLANT_SEGMENT_HEIGHT_PIXELS = 50 # pixels
# PLANT_BASE_SIZE_PIXELS = (180, 180) # pixels
# PLANT_HEAD_SIZE_PIXELS = (240, 89) # pixels





# formula for speed is:
"""
0.4 * current height / FPS
"""
STARTING_SPEED = (PLANT_SEGMENT_HEIGHT * 2.0) / FPS # meters/ 60s
SPEED_FALLOFF_PARAM = 0.1

# Heights for my objects in meters
COCKROACH_HEIGHT = 0.05  # meters
MOUSE_HEIGHT = 0.1       # meters
CAR_HEIGHT = 1.5          # meters
PERSON_HEIGHT = 1.7       # meters
BEAR_HEIGHT = 3         # meters

# Buildings (scaled from PERSON_HEIGHT)
BUILDING1_HEIGHT  = PERSON_HEIGHT * 2.5
BUILDING2_HEIGHT  = PERSON_HEIGHT * 2.5
BUILDING3_HEIGHT  = 2 * PERSON_HEIGHT * 2.5
BUILDING4_HEIGHT  = PERSON_HEIGHT * 2.5
BUILDING5_HEIGHT  = PERSON_HEIGHT * 2.5
BUILDING6_HEIGHT  = 2 * PERSON_HEIGHT * 2.5
BUILDING7_HEIGHT  = 2 * PERSON_HEIGHT * 2.5

# Medium towers (6–12 stories)
BUILDING8_HEIGHT  = 2 * 2 * PERSON_HEIGHT * 2.5
BUILDING9_HEIGHT  = 1.5 * 2 * PERSON_HEIGHT * 2.5
BUILDING10_HEIGHT = 2.5 * 2 * PERSON_HEIGHT * 2.5
BUILDING11_HEIGHT = 3 * 2 * PERSON_HEIGHT * 2.5
BUILDING12_HEIGHT = 2.5 * 2 * PERSON_HEIGHT
BUILDING13_HEIGHT = 3 * 2 * PERSON_HEIGHT * 2.5
BUILDING14_HEIGHT = 2 * 2 * PERSON_HEIGHT * 2.5

# Skyscrapers (20+ stories)
BUILDING15_HEIGHT = 5 * 2 * PERSON_HEIGHT * 2.5
BUILDING16_HEIGHT = 4 * 2 * PERSON_HEIGHT * 2.5



